wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1687237867.339724
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 17
      - 23
      - 37
      4: 3.10.11
      5: 0.15.4
      8:
      - 3
      - 5
